begin;

delete from public.places
where source = 'sproutscout_pilot_20260716';

insert into public.places (
  source,
  source_place_id,
  name,
  category,
  description,
  address_text,
  website_url,
  indoor_outdoor,
  min_age_months,
  max_age_months,
  price_band,
  amenities,
  verification_notes,
  manually_reviewed_at,
  is_active
)
values
  (
    'sproutscout_pilot_20260716',
    'hoboken-public-library',
    'Hoboken Public Library',
    'library',
    null,
    'Hoboken, NJ',
    'https://hobokenlibrary.org',
    'indoor',
    0,
    96,
    'free',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify current childrens programming and branch hours before recommending. Source owner: Hoboken Public Library.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'hoboken-pier-c-park',
    'Pier C Park',
    'playground',
    null,
    'Hoboken, NJ',
    'https://www.hobokennj.gov/resources/pier-c-park',
    'outdoor',
    12,
    96,
    'free',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify weather and any temporary park notices before recommending. Source owner: City of Hoboken.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'hoboken-southwest-resiliency-park',
    'Southwest Resiliency Park',
    'park',
    null,
    'Hoboken, NJ',
    'https://www.hobokennj.gov/resources/southwest-resiliency-park',
    'outdoor',
    12,
    96,
    'free',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify splash or playground availability seasonally before recommending. Source owner: City of Hoboken.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'jersey-city-free-public-library',
    'Jersey City Free Public Library',
    'library',
    null,
    'Jersey City, NJ',
    'https://www.jclibrary.org',
    'indoor',
    0,
    96,
    'free',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify selected branch schedule and event age range before recommending. Source owner: Jersey City Free Public Library.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'liberty-state-park',
    'Liberty State Park',
    'park',
    null,
    'Jersey City, NJ',
    'https://dep.nj.gov/parksandforests/parks/liberty-state-park/',
    'outdoor',
    0,
    96,
    'free',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify weather parking and any park alerts before recommending. Source owner: New Jersey DEP Parks and Forests.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'liberty-science-center',
    'Liberty Science Center',
    'museum',
    null,
    'Jersey City, NJ',
    'https://lsc.org',
    'indoor',
    24,
    96,
    'paid',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify admission timed tickets and exhibit age fit before recommending. Source owner: Liberty Science Center.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'hamilton-park-jersey-city',
    'Hamilton Park',
    'playground',
    null,
    'Jersey City, NJ',
    'https://www.jerseycitynj.gov/cityhall/dpw/parks',
    'outdoor',
    12,
    96,
    'free',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify playground status and restroom availability before recommending. Source owner: Hamilton Park Conservancy and City of Jersey City.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'van-vorst-park',
    'Van Vorst Park',
    'playground',
    null,
    'Jersey City, NJ',
    'https://www.jerseycitynj.gov/cityhall/dpw/parks',
    'outdoor',
    12,
    96,
    'free',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify playground status and restroom availability before recommending. Source owner: City of Jersey City.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'pershing-field-park',
    'Pershing Field Park',
    'park',
    null,
    'Jersey City, NJ',
    'https://www.jerseycitynj.gov/cityhall/dpw/parks',
    'mixed',
    12,
    96,
    'free',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify seasonal facilities and hours before recommending. Source owner: City of Jersey City.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'weehawken-waterfront-park',
    'Weehawken Waterfront Park',
    'waterfront',
    null,
    'Weehawken, NJ',
    'https://www.weehawken-nj.us',
    'outdoor',
    0,
    96,
    'free',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify parking stroller route and weather before recommending. Source owner: Weehawken Township.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'overpeck-county-park',
    'Overpeck County Park',
    'park',
    null,
    'Leonia, NJ',
    'https://www.co.bergen.nj.us/parks-recreation-areas/overpeck-county-park',
    'outdoor',
    0,
    96,
    'free',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify current county park notices and playground details before recommending. Source owner: Bergen County.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'bergen-county-zoo',
    'Bergen County Zoo',
    'zoo',
    null,
    'Paramus, NJ',
    'https://www.co.bergen.nj.us/bergen-county-zoo',
    'mixed',
    18,
    96,
    'paid',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify admission hours train schedule and weather before recommending. Source owner: Bergen County.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'van-saun-county-park',
    'Van Saun County Park',
    'park',
    null,
    'Paramus, NJ',
    'https://www.co.bergen.nj.us/parks-recreation-areas/van-saun-county-park',
    'outdoor',
    0,
    96,
    'free',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify playground carousel and train availability before recommending. Source owner: Bergen County.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'tenafly-nature-center',
    'Tenafly Nature Center',
    'park',
    null,
    'Tenafly, NJ',
    'https://tenaflynaturecenter.org',
    'outdoor',
    24,
    96,
    'under_30',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify trail conditions programs and stroller suitability before recommending. Source owner: Tenafly Nature Center.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'flat-rock-brook',
    'Flat Rock Brook Nature Center',
    'park',
    null,
    'Englewood, NJ',
    'https://www.flatrockbrook.org',
    'outdoor',
    24,
    96,
    'free',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify trail conditions and nature center hours before recommending. Source owner: Flat Rock Brook Nature Association.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'montclair-art-museum',
    'Montclair Art Museum',
    'museum',
    null,
    'Montclair, NJ',
    'https://www.montclairartmuseum.org',
    'indoor',
    36,
    96,
    'paid',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify family programs admission and open galleries before recommending. Source owner: Montclair Art Museum.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'montclair-public-library',
    'Montclair Public Library',
    'library',
    null,
    'Montclair, NJ',
    'https://montclairlibrary.org',
    'indoor',
    0,
    96,
    'free',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify childrens room hours and event registration before recommending. Source owner: Montclair Public Library.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'eagle-rock-reservation',
    'Eagle Rock Reservation',
    'park',
    null,
    'West Orange, NJ',
    'https://parks.essexcountynj.org/parks/eagle-rock-reservation',
    'outdoor',
    0,
    96,
    'free',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify parking trail conditions and weather before recommending. Source owner: Essex County Parks.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'turtle-back-zoo',
    'Turtle Back Zoo',
    'zoo',
    null,
    'West Orange, NJ',
    'https://turtlebackzoo.com',
    'mixed',
    18,
    96,
    'paid',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify tickets hours and weather before recommending. Source owner: Turtle Back Zoo.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'south-mountain-reservation',
    'South Mountain Reservation',
    'park',
    null,
    'West Orange, NJ',
    'https://parks.essexcountynj.org/parks/south-mountain-reservation',
    'outdoor',
    0,
    96,
    'free',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify trail route stroller suitability and weather before recommending. Source owner: Essex County Parks.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'newark-museum-of-art',
    'The Newark Museum of Art',
    'museum',
    null,
    'Newark, NJ',
    'https://newarkmuseumart.org',
    'indoor',
    24,
    96,
    'paid',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify family programming admission and gallery status before recommending. Source owner: The Newark Museum of Art.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'newark-public-library',
    'Newark Public Library',
    'library',
    null,
    'Newark, NJ',
    'https://npl.org',
    'indoor',
    0,
    96,
    'free',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify branch hours and childrens event age range before recommending. Source owner: Newark Public Library.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'branch-brook-park',
    'Branch Brook Park',
    'park',
    null,
    'Newark, NJ',
    'https://parks.essexcountynj.org/parks/branch-brook-park',
    'outdoor',
    0,
    96,
    'free',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify seasonal conditions and restroom availability before recommending. Source owner: Essex County Parks.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'brookdale-park',
    'Brookdale Park',
    'park',
    null,
    'Bloomfield, NJ',
    'https://parks.essexcountynj.org/parks/brookdale-park',
    'outdoor',
    0,
    96,
    'free',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify playground status restroom availability and weather before recommending. Source owner: Essex County Parks.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'reeves-reed-arboretum',
    'Reeves-Reed Arboretum',
    'park',
    null,
    'Summit, NJ',
    'https://reeves-reedarboretum.org',
    'outdoor',
    24,
    96,
    'unknown',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify admission event registration and stroller route before recommending. Source owner: Reeves-Reed Arboretum.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'visual-arts-center-of-new-jersey',
    'Visual Arts Center of New Jersey',
    'museum',
    null,
    'Summit, NJ',
    'https://www.artcenternj.org',
    'indoor',
    48,
    96,
    'paid',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify child class age ranges and registration before recommending. Source owner: Visual Arts Center of New Jersey.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'morris-museum',
    'Morris Museum',
    'museum',
    null,
    'Morristown, NJ',
    'https://morrismuseum.org',
    'indoor',
    36,
    96,
    'paid',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify family exhibit suitability hours and admission before recommending. Source owner: Morris Museum.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'frelinghuysen-arboretum',
    'Frelinghuysen Arboretum',
    'park',
    null,
    'Morristown, NJ',
    'https://www.morrisparks.net/parks_trails/frelinghuysen-arboretum/',
    'outdoor',
    0,
    96,
    'free',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify grounds access and visitor center hours before recommending. Source owner: Morris County Park Commission.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'fosterfields-living-historical-farm',
    'Fosterfields Living Historical Farm',
    'farm',
    null,
    'Morristown, NJ',
    'https://www.morrisparks.net/parks_trails/fosterfields-living-historical-farm/',
    'outdoor',
    24,
    96,
    'paid',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify seasonal schedule tickets and animal area status before recommending. Source owner: Morris County Park Commission.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'great-swamp-outdoor-education-center',
    'Great Swamp Outdoor Education Center',
    'park',
    null,
    'Chatham, NJ',
    'https://www.morrisparks.net/parks_trails/great-swamp-outdoor-education-center/',
    'mixed',
    24,
    96,
    'unknown',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify program schedule trail conditions and stroller suitability before recommending. Source owner: Morris County Park Commission.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'trailside-nature-science-center',
    'Trailside Nature and Science Center',
    'park',
    null,
    'Mountainside, NJ',
    'https://ucnj.org/parks-recreation/trailside-nature-science-center/',
    'mixed',
    24,
    96,
    'free',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify center hours trail conditions and program age range before recommending. Source owner: Union County.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'cora-hartshorn-arboretum',
    'Cora Hartshorn Arboretum',
    'park',
    null,
    'Short Hills, NJ',
    'https://hartshornarboretum.org',
    'outdoor',
    24,
    96,
    'unknown',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify trail conditions and family program registration before recommending. Source owner: Cora Hartshorn Arboretum.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'imagine-that-childrens-museum',
    'Imagine That Childrens Museum',
    'indoor_play',
    null,
    'Florham Park, NJ',
    'https://imaginethatmuseum.com',
    'indoor',
    12,
    72,
    'paid',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify admission hours and toddler age fit before recommending. Source owner: Imagine That.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'westfield-memorial-library',
    'Westfield Memorial Library',
    'library',
    null,
    'Westfield, NJ',
    'https://wmlnj.org',
    'indoor',
    0,
    96,
    'free',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify childrens event schedule and registration before recommending. Source owner: Westfield Memorial Library.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'ridgewood-public-library',
    'Ridgewood Public Library',
    'library',
    null,
    'Ridgewood, NJ',
    'https://www.ridgewoodlibrary.org',
    'indoor',
    0,
    96,
    'free',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify childrens room hours and event age range before recommending. Source owner: Ridgewood Public Library.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'brooklyn-childrens-museum',
    'Brooklyn Childrens Museum',
    'museum',
    null,
    'Brooklyn, NY',
    'https://www.brooklynkids.org',
    'indoor',
    6,
    96,
    'paid',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify admission hours and exhibit availability before recommending. Source owner: Brooklyn Childrens Museum.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'childrens-museum-of-manhattan',
    'Childrens Museum of Manhattan',
    'museum',
    null,
    'New York, NY',
    'https://cmom.org',
    'indoor',
    6,
    96,
    'paid',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify timed entry and current exhibits before recommending. Source owner: Childrens Museum of Manhattan.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'american-museum-natural-history',
    'American Museum of Natural History',
    'museum',
    null,
    'New York, NY',
    'https://www.amnh.org',
    'indoor',
    24,
    96,
    'paid',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify tickets entrance logistics and family exhibit fit before recommending. Source owner: American Museum of Natural History.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'bronx-zoo',
    'Bronx Zoo',
    'zoo',
    null,
    'Bronx, NY',
    'https://bronxzoo.com',
    'mixed',
    18,
    96,
    'paid',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify tickets hours and weather before recommending. Source owner: Bronx Zoo.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'central-park-zoo',
    'Central Park Zoo',
    'zoo',
    null,
    'New York, NY',
    'https://centralparkzoo.com',
    'mixed',
    18,
    96,
    'paid',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify tickets hours and weather before recommending. Source owner: Central Park Zoo.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'queens-zoo',
    'Queens Zoo',
    'zoo',
    null,
    'Queens, NY',
    'https://queenszoo.com',
    'mixed',
    18,
    96,
    'paid',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify tickets hours and weather before recommending. Source owner: Queens Zoo.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'prospect-park-zoo',
    'Prospect Park Zoo',
    'zoo',
    null,
    'Brooklyn, NY',
    'https://prospectparkzoo.com',
    'mixed',
    18,
    96,
    'paid',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify tickets hours and weather before recommending. Source owner: Prospect Park Zoo.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'new-york-aquarium',
    'New York Aquarium',
    'zoo',
    null,
    'Brooklyn, NY',
    'https://nyaquarium.com',
    'mixed',
    18,
    96,
    'paid',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify tickets hours and exhibit status before recommending. Source owner: New York Aquarium.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'brooklyn-bridge-park',
    'Brooklyn Bridge Park',
    'waterfront',
    null,
    'Brooklyn, NY',
    'https://www.brooklynbridgepark.org',
    'outdoor',
    0,
    96,
    'free',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify weather pier access and playground status before recommending. Source owner: Brooklyn Bridge Park.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'prospect-park',
    'Prospect Park',
    'park',
    null,
    'Brooklyn, NY',
    'https://www.prospectpark.org',
    'outdoor',
    0,
    96,
    'free',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify weather restroom location and any park alerts before recommending. Source owner: Prospect Park Alliance.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'central-park',
    'Central Park',
    'park',
    null,
    'New York, NY',
    'https://www.centralparknyc.org',
    'outdoor',
    0,
    96,
    'free',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify playground choice weather and restroom access before recommending. Source owner: Central Park Conservancy.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'riverside-park',
    'Riverside Park',
    'park',
    null,
    'New York, NY',
    'https://riversideparknyc.org',
    'outdoor',
    0,
    96,
    'free',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify playground location weather and stroller route before recommending. Source owner: Riverside Park Conservancy.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'battery-playscape',
    'Battery Playscape',
    'playground',
    null,
    'New York, NY',
    'https://www.thebattery.org',
    'outdoor',
    12,
    96,
    'free',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify playground status weather and restroom access before recommending. Source owner: Battery Conservancy.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'governors-island',
    'Governors Island',
    'park',
    null,
    'New York, NY',
    'https://www.govisland.com',
    'outdoor',
    0,
    96,
    'unknown',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify ferry schedule seasonal access and weather before recommending. Source owner: Trust for Governors Island.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'hudson-river-park',
    'Hudson River Park',
    'waterfront',
    null,
    'New York, NY',
    'https://hudsonriverpark.org',
    'outdoor',
    0,
    96,
    'free',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify pier selection weather and restroom access before recommending. Source owner: Hudson River Park Trust.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'little-island',
    'Little Island',
    'park',
    null,
    'New York, NY',
    'https://littleisland.org',
    'outdoor',
    0,
    96,
    'free',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify entry requirements events and weather before recommending. Source owner: Little Island.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'domino-park',
    'Domino Park',
    'waterfront',
    null,
    'Brooklyn, NY',
    'https://www.dominopark.com',
    'outdoor',
    0,
    96,
    'free',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify playground and water feature availability before recommending. Source owner: Domino Park.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'pier-57',
    'Market 57 and Rooftop Park',
    'waterfront',
    null,
    'New York, NY',
    'https://pier57nyc.com',
    'mixed',
    0,
    96,
    'free',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify indoor food hall hours rooftop access and crowd suitability before recommending. Source owner: Pier 57.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'high-line',
    'The High Line',
    'park',
    null,
    'New York, NY',
    'https://www.thehighline.org',
    'outdoor',
    0,
    96,
    'free',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify stroller elevator access weather and crowd expectations before recommending. Source owner: The High Line.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'brooklyn-botanic-garden',
    'Brooklyn Botanic Garden',
    'park',
    null,
    'Brooklyn, NY',
    'https://www.bbg.org',
    'outdoor',
    0,
    96,
    'paid',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify admission hours and stroller route before recommending. Source owner: Brooklyn Botanic Garden.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'new-york-hall-of-science',
    'New York Hall of Science',
    'museum',
    null,
    'Queens, NY',
    'https://nysci.org',
    'indoor',
    24,
    96,
    'paid',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify exhibit status admission and age fit before recommending. Source owner: New York Hall of Science.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'staten-island-childrens-museum',
    'Staten Island Childrens Museum',
    'museum',
    null,
    'Staten Island, NY',
    'https://www.sichildrensmuseum.org',
    'indoor',
    12,
    96,
    'paid',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify admission hours and exhibit availability before recommending. Source owner: Staten Island Childrens Museum.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'queens-botanical-garden',
    'Queens Botanical Garden',
    'park',
    null,
    'Queens, NY',
    'https://queensbotanical.org',
    'outdoor',
    0,
    96,
    'unknown',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify admission season and stroller route before recommending. Source owner: Queens Botanical Garden.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'socrates-sculpture-park',
    'Socrates Sculpture Park',
    'park',
    null,
    'Queens, NY',
    'https://socratessculpturepark.org',
    'outdoor',
    0,
    96,
    'free',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify weather current exhibition and restroom access before recommending. Source owner: Socrates Sculpture Park.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'wave-hill',
    'Wave Hill',
    'park',
    null,
    'Bronx, NY',
    'https://www.wavehill.org',
    'outdoor',
    0,
    96,
    'paid',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify admission hours and stroller route before recommending. Source owner: Wave Hill.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'new-york-transit-museum',
    'New York Transit Museum',
    'museum',
    null,
    'Brooklyn, NY',
    'https://www.nytransitmuseum.org',
    'indoor',
    24,
    96,
    'paid',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify admission hours stroller policy and exhibit access before recommending. Source owner: New York Transit Museum.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'sugar-hill-childrens-museum',
    'Sugar Hill Childrens Museum',
    'museum',
    null,
    'New York, NY',
    'https://www.sugarhillmuseum.org',
    'indoor',
    24,
    96,
    'paid',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify hours programming and age fit before recommending. Source owner: Sugar Hill Childrens Museum.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'staten-island-zoo',
    'Staten Island Zoo',
    'zoo',
    null,
    'Staten Island, NY',
    'https://www.statenislandzoo.org',
    'mixed',
    18,
    96,
    'paid',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify tickets hours and weather before recommending. Source owner: Staten Island Zoo.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'queens-museum',
    'Queens Museum',
    'museum',
    null,
    'Queens, NY',
    'https://queensmuseum.org',
    'indoor',
    36,
    96,
    'unknown',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify family program schedule admission and open galleries before recommending. Source owner: Queens Museum.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'brooklyn-public-library-central',
    'Brooklyn Public Library Central Library',
    'library',
    null,
    'Brooklyn, NY',
    'https://www.bklynlibrary.org/locations/central',
    'indoor',
    0,
    96,
    'free',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify childrens room hours and event age range before recommending. Source owner: Brooklyn Public Library.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'nypl-stavros-niarchos-foundation-library',
    'Stavros Niarchos Foundation Library',
    'library',
    null,
    'New York, NY',
    'https://www.nypl.org/locations/snfl',
    'indoor',
    0,
    96,
    'free',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify childrens programming and branch hours before recommending. Source owner: New York Public Library.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'nypl-53rd-street-library',
    '53rd Street Library',
    'library',
    null,
    'New York, NY',
    'https://www.nypl.org/locations/53rd-street',
    'indoor',
    0,
    96,
    'free',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify branch hours and family program schedule before recommending. Source owner: New York Public Library.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'queens-public-library-flushing',
    'Queens Public Library at Flushing',
    'library',
    null,
    'Queens, NY',
    'https://www.queenslibrary.org/about-us/locations/Flushing',
    'indoor',
    0,
    96,
    'free',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify branch hours and family program age range before recommending. Source owner: Queens Public Library.',
    '2026-07-16 00:00:00-04',
    true
  ),
  (
    'sproutscout_pilot_20260716',
    'brooklyn-public-library-brooklyn-heights',
    'Brooklyn Heights Library',
    'library',
    null,
    'Brooklyn, NY',
    'https://www.bklynlibrary.org/locations/brooklyn-heights',
    'indoor',
    0,
    96,
    'free',
    '{"strollerFriendly": "unknown", "bathroomAvailable": "unknown", "parkingAvailable": "unknown"}'::jsonb,
    'Verify branch hours and childrens area availability before recommending. Source owner: Brooklyn Public Library.',
    '2026-07-16 00:00:00-04',
    true
  );

commit;
